<?php

namespace App\Models;

use App\Scopes\Franchise\FranchiseScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderAditional extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'order_id',
        'aditional_id',
        'quantity',
        'price',
        'discount',
        'total'
    ];

    protected $table = 'order_aditionals';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new FranchiseScope());
    }

    public function aditional()
    {
        return $this->hasOne(Aditional::class, 'id', 'aditional_id');
    }

}
